seed: 59
ckpt_path: null
train: True
test: True

defaults:
  - _self_
  - hydra: default
  - paths: default
  - trainer: default
  - data: PhoMT
  - model: transformer
  - logger: null
  - experiment: null
